const challenges = [
  {g:1,s:'math',t:'Maths',title:'Number bonds to 10',short:'Use hidden peanuts to discover the pairs that make ten.',time:'45–60 min',prep:'10 small objects and two bowls',why:'Fluent number bonds make later calculation feel possible, not mysterious.',do:'Put 10 counters on a plate. Hide some under a bowl. Ask: “How many can you see? How many are hiding?” Let your child explain how they know.',ask:'What did you notice about the pairs? Can you find a faster way than counting?',apply:'Spot pairs that make 10 during the week—on a bus, with fruit, or at the dinner table.'},
  {g:1,s:'english',t:'English',title:'The sound detective',short:'Hear, stretch and blend the sounds inside words.',time:'30–45 min',prep:'Paper, pencil and a few tiny household objects',why:'A sequenced phonics habit helps children become confident independent readers.',do:'Choose a simple object such as a cup or pen. Say its sounds slowly. Your child pushes a counter for each sound, then blends them back into the whole word.',ask:'Which sound comes first? What word would you get if we changed the first sound?',apply:'Play “sound detective” with three objects each day.'},
  {g:1,s:'science',t:'Science',title:'What do plants need?',short:'Run a seed-cup test and learn to notice evidence.',time:'Across 5–7 days',prep:'Three cups, seeds, cotton and water',why:'Early science is about observing, comparing and recording—not memorising facts.',do:'Set up three seed cups: one with water and light, one without water, one without light. Draw what you notice each day.',ask:'What changed? Was it a fair test? What did we keep the same?',apply:'Choose one plant at home and become its weekly observer.'},
  {g:1,s:'social',t:'Society',title:'Our first family vote',short:'Make a family rule—and see how fair decisions work.',time:'30 min',prep:'Paper and a jar or bowl',why:'Children learn citizenship by practising voice, rules and fairness at home.',do:'Pick a small real choice: Saturday game, dessert or a family chore. Make two options, give each person a vote, count together and honour the result.',ask:'Was the result fair? What if someone did not agree?',apply:'Write one family rule everyone helped create.'},
  {g:1,s:'computing',t:'Computing',title:'Program the parent robot',short:'Give precise instructions, laugh at the bugs, then debug.',time:'30 min',prep:'A clear floor and a small goal object',why:'Computational thinking starts with clear instructions and the courage to improve them.',do:'You are the robot. Your child must guide you to a toy using only exact commands. Follow their words literally—even the silly ones.',ask:'Which instruction was unclear? What should the robot do first?',apply:'Make a four-step “getting ready” algorithm for a school morning.'},
  {g:1,s:'life',t:'Life skills',title:'The feelings thermometer',short:'Name big feelings and build a calm-down plan.',time:'30–40 min',prep:'Paper and colouring pencils',why:'Feelings vocabulary and practical calming tools help children grow resilient and kind.',do:'Draw a thermometer from calm to exploding. Together, add examples of how each level feels in the body and one helpful action for each.',ask:'What helps your body feel safe again? Who can you ask for help?',apply:'Keep the plan somewhere visible and practise it when everyone is calm.'},
  {g:2,s:'math',t:'Maths',title:'Guess, then measure',short:'Estimate first, then use centimetres and metres to find out.',time:'45 min',prep:'Ruler or tape measure, paper',why:'Estimating before measuring builds a strong sense of number and quantity.',do:'Make three guesses: the length of a book, table and room. Measure each, record it and compare with your guess.',ask:'Which guess was closest? What would help you make a better guess next time?',apply:'Plan a room rearrangement using measurements.'},
  {g:2,s:'science',t:'Science',title:'Build a weather station',short:'Make a rain gauge, use a thermometer and tell a weather story.',time:'Across one week',prep:'Plastic bottle, ruler, marker, thermometer if available',why:'Children learn science best when they collect their own data and look for patterns.',do:'Make a simple rain gauge from a bottle. Record the weather each day with a drawing and a number where you can.',ask:'Which day was wettest? What might the clouds tell us?',apply:'Turn the week’s findings into a tiny weather report.'},
  {g:2,s:'life',t:'Life skills',title:'The ₹200 market mission',short:'Spend, save and give with a real-life budget.',time:'45–60 min',prep:'Play money, grocery leaflet or real price list',why:'Money habits grow from everyday decisions, not abstract sums.',do:'Give your child ₹200 in pretend money. They choose items from a real list, keep within budget and divide a little between spend, save and give.',ask:'What did you choose not to buy? What did that choice make possible?',apply:'Let them help plan one small real shopping list.'},
  {g:3,s:'math',t:'Maths',title:'Fractions on a number line',short:'Move fractions from food onto a line where they behave like numbers.',time:'45 min',prep:'Paper strips, marker and scissors',why:'Seeing fractions as numbers unlocks comparison, equivalence and later decimals.',do:'Fold paper strips into halves, thirds and quarters. Mark each on a drawn number line from 0 to 1.',ask:'Which is bigger: one half or one third? How can the line prove it?',apply:'Find fractions in a recipe or a shared snack.'},
  {g:3,s:'computing',t:'Computing',title:'Make a rangoli algorithm',short:'Use patterns, loops and a few well-chosen commands.',time:'45–60 min',prep:'Grid paper and colours',why:'Patterns and repetition are the heart of coding—and can begin away from a screen.',do:'Draw a small repeated rangoli pattern on grid paper. Write instructions for someone else to recreate it, including repeat commands.',ask:'Which steps repeat? How could we make the instructions shorter?',apply:'Ask a family member to test your program and report a bug.'},
  {g:3,s:'social',t:'Society',title:'Who runs our city?',short:'Trace a local problem from question to civic action.',time:'45 min',prep:'Paper and a local neighbourhood example',why:'Civic understanding grows when children see that communities can solve real problems.',do:'Choose one local issue—waste, a broken footpath or water. Map who is involved, what each person can do and one respectful next step.',ask:'Whose job is it? What evidence would convince them?',apply:'Create a two-sentence suggestion for your housing society or local representative.'},
  {g:4,s:'math',t:'Maths',title:'The family picnic budget',short:'Use decimals, estimation and a buffer to plan a real outing.',time:'60 min',prep:'A price list, paper and calculator for checking',why:'Decimals become meaningful when they help children make sensible choices.',do:'Plan snacks, travel and one activity for a picnic. Work within a budget, estimate first, then calculate precisely and keep a 10% buffer.',ask:'Where did our estimate differ from the exact total? What can we change without spoiling the plan?',apply:'Share the final plan with the family and defend one choice.'},
  {g:4,s:'english',t:'English',title:'Write for a real audience',short:'Plan, draft, revise and publish an opinion worth reading.',time:'60–90 min',prep:'Paper or a computer, one real family question',why:'Strong writers do not merely finish a draft—they improve it for a reader.',do:'Choose a genuine question: “Should children have a weekly allowance?” Make a claim, give reasons and evidence, then revise one paragraph for clarity.',ask:'What might someone who disagrees say? Which sentence is doing the most work?',apply:'Read it aloud to a family member and invite one useful suggestion.'},
  {g:4,s:'science',t:'Science',title:'The ramp fair test',short:'Change one thing, measure fairly and improve a design.',time:'45–60 min',prep:'Cardboard, a toy car or marble, books and tape',why:'Fair tests build honesty, problem-solving and confidence with evidence.',do:'Build a ramp. Change only its height, run the car three times and measure how far it travels. Record every result, even the odd ones.',ask:'What did we keep the same? Why repeat a test?',apply:'Redesign the ramp to solve one real challenge: farthest travel or gentlest landing.'},
  {g:4,s:'life',t:'Life skills',title:'Design for a grandparent',short:'Listen, prototype and improve something useful for another person.',time:'90 min+',prep:'Cardboard, tape, scrap materials and a willing interviewee',why:'Empathy becomes practical when children make and improve something for a real person.',do:'Ask a grandparent about a small daily difficulty. Sketch a solution, make a cardboard prototype, test it with them and improve it.',ask:'What did they actually need? What changed after they tried it?',apply:'Present version 1 and version 2, explaining the change.'}
];
const gradeFocus={1:['I can do things myself.','Build number sense, early reading confidence, questions, simple science and safe independence.'],2:['I can plan and make.','Strengthen fluency while your child measures, tests, maps, budgets and creates.'],3:['I can think, decide and help.','Develop evidence, clear communication, practical maths, coding and local citizenship.'],4:['I can lead, question and give back.','Move into deeper inquiry, confident expression, media awareness and real responsibility.']};
let grade=1,filter='all',visible=6;const saved=new Set(JSON.parse(localStorage.getItem('growing-citizens-done')||'[]'));
const grid=document.querySelector('#challengeGrid'),filters=document.querySelector('#filters'),modal=document.querySelector('#challengeModal'),progressModal=document.querySelector('#progressModal');
const labels=[['all','All challenges'],['math','Maths'],['english','English'],['science','Science'],['social','Society'],['computing','Computing'],['life','Life skills']];
function titleCase(s){return s==='social'?'Society':s==='life'?'Life skills':s[0].toUpperCase()+s.slice(1)}
function renderFocus(){const [heading,copy]=gradeFocus[grade];document.querySelector('#gradeFocus').innerHTML=`<strong>Grade ${grade}: “${heading}”</strong>${copy}`;document.querySelectorAll('.grade-choice').forEach(b=>b.classList.toggle('active',+b.dataset.grade===grade));}
function renderFilters(){filters.innerHTML=labels.map(([v,l])=>`<button class="filter ${filter===v?'active':''}" data-filter="${v}">${l}</button>`).join('');filters.querySelectorAll('button').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;visible=6;renderFilters();renderGrid()})}
function renderGrid(){const all=challenges.filter(c=>c.g===grade&&(filter==='all'||c.s===filter));const toShow=all.slice(0,visible);grid.innerHTML=toShow.map(c=>`<article class="challenge"><span class="tag ${c.s}">${c.t.toUpperCase()}</span><h3>${c.title}</h3><p>${c.short}</p><div class="challenge-meta">GRADE ${c.g} · ${c.time.toUpperCase()}</div><button data-title="${c.title}">Open challenge →</button></article>`).join('')||'<p>No challenges in this thread for this grade yet.</p>';grid.querySelectorAll('button').forEach(b=>b.onclick=()=>openChallenge(challenges.find(c=>c.title===b.dataset.title)));document.querySelector('#showMore').style.display=all.length>visible?'inline-flex':'none'}
function openChallenge(c){const done=saved.has(c.title);document.querySelector('#modalContent').innerHTML=`<div class="modal-inner"><span class="tag ${c.s}">${c.t.toUpperCase()} · GRADE ${c.g}</span><h2>${c.title}</h2><p class="modal-meta">${c.time.toUpperCase()} · ${c.prep.toUpperCase()}</p><div class="modal-block"><h3>Why it matters</h3><p>${c.why}</p></div><div class="modal-block"><h3>Try this</h3><p>${c.do}</p></div><div class="modal-block"><h3>Talk together</h3><p>“${c.ask}”</p></div><div class="modal-block"><h3>Take it into the week</h3><p>${c.apply}</p></div><button class="done-button ${done?'done':''}" id="doneButton">${done?'✓ Completed together':'Mark as completed'}</button></div>`;document.querySelector('#doneButton').onclick=()=>toggleDone(c.title);modal.showModal()}
function toggleDone(title){saved.has(title)?saved.delete(title):saved.add(title);localStorage.setItem('growing-citizens-done',JSON.stringify([...saved]));updateProgress();modal.close();renderGrid()}
function updateProgress(){document.querySelector('#progressCount').textContent=saved.size}
document.querySelectorAll('.grade-choice').forEach(b=>b.onclick=()=>{grade=+b.dataset.grade;filter='all';visible=6;renderFocus();renderFilters();renderGrid();document.querySelector('#challenges').scrollIntoView({behavior:'smooth',block:'start'})});
document.querySelector('#showMore').onclick=()=>{visible+=6;renderGrid()};document.querySelectorAll('.modal-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
document.querySelector('#progressButton').onclick=()=>{const list=[...saved];document.querySelector('#progressContent').innerHTML=`<div class="progress-inner"><p class="eyebrow">YOUR FAMILY'S LEARNING PATH</p><h2>Progress, not pressure.</h2><div class="progress-stat">${list.length}</div><p>${list.length===1?'challenge completed':'challenges completed'} together. Every one is a small vote for curiosity.</p>${list.length?`<ul class="progress-list">${list.map(x=>`<li>✓ ${x}</li>`).join('')}</ul>`:'<p class="progress-empty">Your completed challenges will appear here. Pick one that feels doable this weekend.</p>'}</div>`;progressModal.showModal()};
document.querySelector('#resetProgress').onclick=()=>{if(confirm('Reset all completed challenges on this device?')){saved.clear();localStorage.removeItem('growing-citizens-done');updateProgress()}};
renderFocus();renderFilters();renderGrid();updateProgress();
